package com.company.api;

public class BaseApi {

    protected static String TOKEN = "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDgiLCJuYW1lIjpudWxsLCJpZCI6IjEwOCIsInVzZXJuYW1lIjoiTmFzdHlhIiwibGFzdG5hbWUiOm51bGwsImlhdCI6MTYzNDc1ODY5MSwiZXhwIjoxNjM0NzYyMjkxfQ.1pT40g9DtFk37IHbZ1gVbUp4TWHLVsLEWHi_3S4OeQ5nCPSAWiUmdO7XUbGgmI2jYlJibsHmJ64rp3FqRl_Zfw";
}
